#!/bin/bash
# shellcheck disable=SC2068
java -jar wacc-25-compiler.jar $@

# shellcheck disable=SC2037
# shellcheck disable=SC2209
input=$(echo "$*" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')



ecode=$?
if [ $ecode == 100 ] || [ $ecode == 200 ]
then
    exit $ecode
fi

fname=$(basename "$1" .wacc)
arm-linux-gnueabi-gcc -o "${fname}" -mcpu=arm1176jzf-s -mtune=arm1176jzf-s "${fname}.s"

#grab input from wacc file. put it in the speech marks.
echo $input | qemu-arm -L /usr/arm-linux-gnueabi/ "${fname}"

if [ $ecode == 100 ] || [ $ecode == 200 ]
then
  exit $?
fi

mv ${fname} build

exit 0