#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.
# shellcheck disable=SC2068
java -jar wacc-25-compiler.jar $@
bash compile_and_run.sh

exit $?


