#!/bin/bash
# Bash front-end for your compiler.
# You are free to change the language used for this script,
# but do not change its name.
# shellcheck disable=SC2068
java -jar wacc-25-compiler.jar $@

if [ $? != "0" ]
then
    exit $?
fi

fname=$(basename "$1" .wacc)
arm-linux-gnueabi-gcc -o "${fname}" -mcpu=arm1176jzf-s -mtune=arm1176jzf-s "${fname}.s"
qemu-arm -L /usr/arm-linux-gnueabi/ "${fname}"
mv ${fname} build
exit $?